parameters:
  - name: platform
    type: string
  - name: configuration
    type: string

steps:
  - template: checkout.yml

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.8'
    inputs:
      versionSpec: 5.8

  - task: NuGetAuthenticate@1
    displayName: 'NuGet authenticate'

  # Install the GDK package explicitly into $(Pipeline.Workspace)/gdk
  - script: |
      nuget install Microsoft.GDK.Windows -Version 2510.0.6194 -OutputDirectory "%GameDK%" -DirectDownload
      echo "GDK installed to %GameDK%"
      ls "%GameDK%"
      echo "* %GameDK%\Microsoft.GDK.Windows.2510.0.6194"
      ls "%GameDK%\Microsoft.GDK.Windows.2510.0.6194"
      echo "* %GameDK%\Microsoft.GDK.Windows.2510.0.6194\native"
      ls "%GameDK%\Microsoft.GDK.Windows.2510.0.6194\native"
      echo "* %GameDK%\Microsoft.GDK.Windows.2510.0.6194\native\251000"
      ls "%GameDK%\Microsoft.GDK.Windows.2510.0.6194\native\251000"
      echo "* %GameDK%\Microsoft.GDK.Windows.2510.0.6194\native\251000\windows"
      ls "%GameDK%\Microsoft.GDK.Windows.2510.0.6194\native\251000\windows"
      echo "* %GameDKCoreLatest%"
      ls "%GameDKCoreLatest%"
    displayName: 'Install GDK.Windows via NuGet'

  # Install NuGet dependencies. The GUID below is the NuGetCommand for MSFT internal.
  - task: 333b11bd-d341-40d9-afcf-b32d5ce6f23b@2
    displayName: NuGet restore
    inputs:
      restoreSolution: '*.sln'
    continueOnError: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 3.1.411
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: VSBuild@1
    displayName: Build ${{ parameters.platform }}+${{ parameters.configuration }} Solution
    inputs:
      solution: libHttpClient.vs2022.sln
      vsVersion: 17.0
      msbuildArchitecture: x64
      platform: ${{ parameters.platform }}
      configuration: ${{ parameters.configuration }}
      createLogFile: true
      logProjectEvents: true
      logFileVerbosity: 'diagnostic'

